### ISSUE TITLE
 How to FIX Error Status=133 when connecting to BLE devices that are activated from time to time?

### ISSUE THREAD

**Issue by romaruiz** [PunchThrough/ble-starter-android#13]
Hi, I'm getting error 133 to connect a BLE sensor (Temperature and Humidity). I have executed : device.connectGatt(context, false, callback) and device.connectGatt(context, false, callback,2). 2= BluetoothDevice.TRANSPORT_LE but the problem continues. The connectGatt with 4 parameters using SDK 26. Android version 8.0.0
Any guide/tips or workaround for resolved it?

Thks for your advance

To ensure that the mobile device is compatible with this apk, log trace is attached, with:
1) Service discovery and get data OK for another device
2) Error with status = 133, at line 136, for BLE device 

[Log_ble_starter_2022_0202.txt](https://github.com/PunchThrough/ble-starter-android/files/7991082/Log_ble_starter_2022_0202.txt)

**Comment by cheeyi** [comment]
Hi, status error issues are highly dependent on the specific peripheral you're working with. Generally 133 means the connection has failed due to the following reasons:

1. Peripheral is out of range
2. Peripheral is not advertising
3. Peripheral firmware is not accepting the connection request
4. Other issues in the Android Bluetooth stack

As it's hard to debug and peripheral-dependent, and therefore not really related to this project's code, I'm closing the issue.
