### ISSUE TITLE
Connect to several devices

### ISSUE THREAD

**Issue by wiesener** [PunchThrough/ble-starter-android#3]
Hi, 

I am studying your code and I am interested in getting your opinion on how to connect to several devices at the same time. Your ConnectionManager is Singleton as far as I understand. So how is it possible to be connected to several devices at the same time? 

Thanks 

C.W.

**Comment by cheeyi** [comment]
Hi @wiesener, apologies for the delay in response. Our example code only walks through the single-device connection instance and connecting to several devices simultaneously is currently out of scope. That said, you could modify `ConnectionManager` to support multiple devices because each `BleOperationType` is tied to a specific `BluetoothDevice`. It was a conscious effort on our end to ensure this is extensible to the multi-device use case.
